### ISSUE TITLE
Checklist de Atividades

### ISSUE THREAD

**Issue by fabiosvf** [fabiosvf/trilha-nodejs-projeto-02#1]
**RF - Requisitos Funcionais**
- [x] O usuário deve poder criar uma nova transação
- [x] O usuário deve poder obter um resumo da sua conta
- [x] O usuário deve poder listar todas as transações que já ocorreram
- [x] O usuário deve poder visualizar uma transação única

**RN - Requisitos de Negócio**
- [x] A transação pode ser do tipo crédito (que somará ao valor total) ou débito (que subtruairá do valor total)
- [x] Deve ser possível identificarmos o usuário entre as requisições
- [x] O usuário só pode visualizar transações das quais ele criou
